---
- name: Install and configure NGINX
  hosts: poochella
  become: true
  tasks:
    - name: Update package cache
      ansible.builtin.package:
        update_cache: true
        cache_valid_time: 3600

    - name: Install NGINX
      ansible.builtin.package:
        name: nginx
        state: present
      notify:
        - Restart NGINX
  handlers:
    - name: Restart NGINX
      ansible.builtin.service:
        name: nginx
        state: restarted
- name: Build React app locally
  hosts: localhost
  vars:
    repo_url: "https://github.com/Ivanipani/song-viewer.git"
    local_repo_path: "/tmp/song-viewer"
    build_path: "/tmp/song-viewer/dist"
  tasks:
    - name: Clone/pull repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ local_repo_path }}"
        clone: true
        update: true
      register: git_status

    - name: Install npm dependencies
      ansible.builtin.command:
        cmd: npm install
        chdir: "{{ local_repo_path }}"
      when: git_status.changed

    - name: Build React app
      ansible.builtin.command:
        cmd: npm run build
        chdir: "{{ local_repo_path }}"
      when: git_status.changed

- name: Deploy to web server
  hosts: poochella
  vars:
    build_path_src: "/tmp/song-viewer/dist"
    build_path_dest: "/var/www/song-viewer"
    domain: "canciones.poochella.com"
    audio_path_src: "/Users/ivanperdomo/canciones"
    audio_path_dest: "/public/canciones"
  tasks:
    - name: Create web app directory
      ansible.builtin.file:
        path: "{{ build_path_dest }}"
        state: directory
        mode: '0755'
        owner: www-data
        group: www-data
      become: true

    - name: Copy built files to server
      ansible.builtin.copy:
        src: "{{ build_path_src }}/"
        dest: "{{ build_path_dest }}"
        mode: '0644'
      become: true

    - name: Configure NGINX site
      ansible.builtin.template:
        src: nginx-react-app.conf.j2
        dest: /etc/nginx/sites-available/song-viewer
        mode: '0644'
      become: true
      notify: Restart NGINX
    - name: Enable NGINX site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/song-viewer
        dest: /etc/nginx/sites-enabled/song-viewer
        state: link
      become: true
      notify: Restart NGINX
  handlers:
    - name: Restart NGINX
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
